import React from 'react';

export default function EmptyState({ onSelectPreset }) {
  const steps = [
    {
      num: '01',
      title: 'CONNECT REPOSITORY',
      desc: 'Connect your GitHub repository to construct commit, pull request, and issue graphs in Neo4j.'
    },
    {
      num: '02',
      title: 'ASK WHY',
      desc: 'Ask about architectural design choices, code refactors, or bug fixes.'
    },
    {
      num: '03',
      title: 'TRACE THE REASON',
      desc: 'Explore historical evidence and decision chains generated by GraphRAG and Sarvam AI.'
    }
  ];

  return (
    <div className="bg-[#0b1120] border border-[#1a2940] rounded-xs p-8 text-center space-y-6">
      
      {/* ABSTRACT PRODUCT MARK & HERO TITLE */}
      <div className="space-y-2 max-w-xl mx-auto flex flex-col items-center">
        <div className="w-8 h-8 rounded-xs bg-[#00afc4] flex items-center justify-center font-mono font-bold text-sm text-[#070b16] mb-1">
          ?
        </div>

        <h2 className="text-xl md:text-2xl font-bold tracking-tight text-[#e8edf7] font-mono uppercase">
          WHY THE CODE IS LIKE THIS
        </h2>

        <p className="text-xs text-[#00afc4] font-mono font-semibold">
          Understand the decisions behind the code.
        </p>

        <p className="text-xs text-[#7f8ca3] font-sans leading-relaxed pt-1">
          An interactive code archaeology tool that connects GitHub history to Neo4j graph retrieval to answer why code evolved.
        </p>
      </div>

      {/* THREE INSTRUCTION BLOCKS */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-3 text-left max-w-4xl mx-auto pt-2">
        {steps.map(step => (
          <div
            key={step.num}
            className="p-4 bg-[#0e1627] border border-[#1a2940] rounded-xs space-y-1.5"
          >
            <div className="flex items-center gap-2 font-mono text-xs font-bold text-[#00afc4]">
              <span>{step.num}</span>
              <span>{step.title}</span>
            </div>
            <p className="text-[11px] text-[#7f8ca3] font-sans leading-relaxed">
              {step.desc}
            </p>
          </div>
        ))}
      </div>

      {/* DEMO ACTION BUTTON */}
      <div className="pt-2">
        <button
          onClick={() => onSelectPreset && onSelectPreset('expressjs/express')}
          className="inline-flex items-center gap-2 bg-[#6754f5] hover:bg-[#5241db] text-[#ffffff] font-mono text-xs font-semibold px-5 py-2.5 rounded-xs transition-colors duration-150 cursor-pointer"
        >
          <span>Explore expressjs/express</span>
          <span>→</span>
        </button>
      </div>

    </div>
  );
}
